services:
  - type: web
    name: luma-sistema
    env: python
    plan: free
    region: ohio
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn mi_tienda.wsgi:application
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DISABLE_COLLECTSTATIC
        value: "0"
      - key: PYTHON_VERSION
        value: "3.10.0"

  - type: postgresql  # Â¡CORREGIDO! era "pgsql" y debe ser "postgresql"
    name: luma-database
    plan: free
    ipAllowList: []