services:
  - type: web
    name: luma-sistema
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mi_tienda.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4